name: Compile
run-name: Complie The C
on: push
jobs:
  C:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - run: gcc --version
      - run: ls -l
      - run: gcc i1.c -o i1.out
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.out"
        bodyFile: "body.md"
