name: Build and Push C Code

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Compile C code
        run: |
          gcc i1.c -o i1.out

      - name: Push output
        uses: actions/upload-artifact@v3
        with:
          name: compiled-code
          path: ./i1.out  # Replace output with the actual output file name

      - name: Grant permissions (optional)
        run: chmod +x i1.out  # Makes the output executable (optional)
