name: Build and Release (Linux)

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build the C program
        run: |
          gcc i1.c -o i1  # Adjust this command based on your build system (e.g., CMake)
        working-directory: ${{ github.workspace }}  # Ensure builds happen in the project directory

      - name: Create artifact
        run: |
          mv i1 output_linux  # Adjust output file name and path

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: ${{ github.workspace }}/output_linux

  release:
    needs: build  # Wait for the build job to complete before releasing
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Create release
        uses: actions/create-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use a release token
        with:
          tag_name: ${{ github.sha }}  # Use commit SHA as release tag
          release_name: Build ${{ github.sha }}
          body: |
            Built and tested on Linux

          draft: false  # Create a public release

